### ISSUE TITLE
english

### ISSUE THREAD

**Issue by cobra85ec** [kiwimato/invoiceninja-v5-unraid#4]
how do u add a region.. english usa

**Comment by kiwimato** [comment]
I'm sorry, but that is more of a Invoiceninja issue, this repository only contains the part that makes Invoiceninja work on unRAID. I think information like that you'll find on the actual Invoice Ninja forum: https://forum.invoiceninja.com/

However, I took a look and I assume it would be in this location, but I'm not sure this is what you're looking for.

![image](https://user-images.githubusercontent.com/56123381/204659698-7a4c85fe-f404-42b7-80ed-a5a0332bb285.png)

**Comment by cobra85ec** [comment]
do have any better install info...?

**Comment by kiwimato** [comment]
Nothing more than what's already in the Readme, but if you tell me what's not clear enough from there, I will update it.

**Comment by cobra85ec** [comment]
its not at all... do i install from the app section in unraid 1st

**Comment by kiwimato** [comment]
yes, that's how you install all apps in unRAID

**Comment by cobra85ec** [comment]
from maihai/invoiceninja_v5 ?

**Comment by cobra85ec** [comment]
ok i created the new db called invoiceninja5

after the install is done what do i do..>

**Comment by kiwimato** [comment]
you login into the app with the credentials you set as environment variables?

**Comment by cobra85ec** [comment]
yes...
